src/Form/ActivityFormType.php
<?php
declare(strict_types=1);

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use App\Form\Model\Activity\MovementActivityFormModel;
use App\Form\Model\Activity\AbstractActivityFormModel;
use App\Form\Model\Activity\BodyweightActivityFormModel;
use App\Form\Model\Activity\WeightActivityFormModel;

class ActivityFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $activity = $options['data'] ?? null;
        $isEdit = $activity && $activity->getId();

        $builder
            ->add('type', ChoiceType::class, [
                'placeholder' => 'Choose type',
                'choices' => $this->getChoices('activity_type'),
                'disabled' => $isEdit
            ])
            ->add('name', TextType::class)
        ;

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) {
                /** @var BasicActivityFormModel|null $data */
                $data = $event->getData();
                if (!$data) {
                    return;
                }
                
                $this->setupSpecificActivityField(
                    $event->getForm(),
                    $data->getType()
                );
            }
        );

        $builder->get('type')->addEventListener(
            FormEvents::POST_SUBMIT,
            function(FormEvent $event) {
                $form = $event->getForm();
                $this->setupSpecificActivityField(
                    $form->getParent(),
                    $form->getData()
                );
            }
        );
       
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }


    private function setupSpecificActivityField(FormInterface $form, ?string $type)
    {   
        $form
            ->add('energy', IntegerType::class)
            ;
        switch ($type) {
            case 'Movement':
                $form
                    ->add('intensity', ChoiceType::class, [
                        'placeholder' => 'Choose intensity',
                        'choices' => $this->getChoices('movement_intensity'),
                    ])
                    ->add('speedAverageMin', NumberType::class)
                    ->add('speedAverageMax', NumberType::class)
                ;
                break;
            case 'MovementSet':
                $form
                    ->remove('energy')//this type of activity don't need energy (Energy from sets activities will be used)
                    ;
                break;
            case 'Bodyweight':
                $form
                    ->add('repetitionsAvgMin', IntegerType::class)
                    ->add('repetitionsAvgMax', IntegerType::class)
                    ->add('intensity', ChoiceType::class, [
                        'placeholder' => 'Choose intensity',
                        'choices' => $this->getChoices('bodyweight_intensity'),
                    ])
                    ;
                break;
            case 'Weight':
                $form
                    ->add('repetitionsAvgMin', IntegerType::class)
                    ->add('repetitionsAvgMax', IntegerType::class)
                    ->add('weightAvgMin', NumberType::class)   
                    ->add('weightAvgMax', NumberType::class)   
                ;
        }
    }

    private function getChoices(string $fieldName)
    {   
        switch ($fieldName) {
            case 'activity_type':
                return AbstractActivityFormModel::getAvaibleTypes();
            case 'movement_intensity':
                return MovementActivityFormModel::getAvaibleIntensities();
            case 'bodyweight_intensity':
                return BodyweightActivityFormModel::getAvaibleIntensities();
        }
    }

}

src/Form/CuriosityFormType.php
<?php
declare(strict_types=1);

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Validator\Constraints\Image;
use App\Form\Model\Curiosity\CuriosityFormModel;

class CuriosityFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $curiosity = $options['data'] ?? null;
        $isEdit = $curiosity && $curiosity->getId();

        $imageConstraints = [
            new Image([
                'maxSize' => '5M',
                'maxRatio' => 1.75,
                'maxRatioMessage' => 
                    'Uploaded image will be resized to make site content user friendly.
                    Your image ratio is too big ({{ ratio }}) and will be ugly after resize.
                    Allowed maximum ratio is {{ max_ratio }}. Please change it.',
                'mimeTypes' => [
                    'image/jpeg',
                    'image/png',
                ]
            ])
        ];

        $builder
            ->add('title', TextType::class, [
                'attr' =>[
                    'placeholder' => 'Enter title of curiosity here.',
                ]
            ])
            ->add('description', TextType::class, [
                'attr' => [
                    'placeholder' => 'Enter short description of curiosity here.',
                ],
                'help' => 'This will be shown on the main page. Think of something catchy!',
            ])
            ->add('content', TextareaType::class, [
                'attr' => [
                    'placeholder' => 'Enter content of curiosity here.',
                ],
                'required' => false
            ])
            ->add('isPublished', CheckboxType::class, [
                'required' => false,
            ])
            ->add('imageFile', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => $imageConstraints,
            ])
        ;

        if ($isEdit) {
            $builder
                ->add('author', UserSelectTextType::class, [
                    'disabled' => true,
                ])
                ->add('id', HiddenType::class)
                ;
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CuriosityFormModel::class,
            'error_mapping' => [
                'mainImageFilename' => 'imageFile'
            ],
        ]);
    }
}

src/Form/CustomTimeType.php
<?php
declare(strict_types=1);

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use App\Form\DataTransformer\DurationToSecondsTransformer;
use Symfony\Component\Routing\RouterInterface;

use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\ReversedTransformer;


class CustomTimeType extends AbstractType 
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
                
        $hourOptions = $minuteOptions = $secondOptions = [
            'error_bubbling' => true,
            'empty_data' => '',
        ];

        // Append generic carry-along options
        foreach (['required', 'translation_domain'] as $passOpt) {
            $hourOptions[$passOpt] = $options[$passOpt];
            $minuteOptions[$passOpt] = $options[$passOpt];
            $secondOptions[$passOpt] = $options[$passOpt];
        }

        // when the form is compound the entries of the array are ignored in favor of children data
        // so we need to handle the cascade setting here
        $emptyData = $builder->getEmptyData() ?: [];

        if (isset($emptyData['hour'])) {
            $hourOptions['empty_data'] = $emptyData['hour'];
        }
        if (isset($emptyData['minute'])) {
            $minuteOptions['empty_data'] = $emptyData['minute'];
        }
        if (isset($emptyData['second'])) {
            $secondOptions['empty_data'] = $emptyData['second'];
        }


        if (isset($options['invalid_message'])) {
            $hourOptions['invalid_message'] = $options['invalid_message'];
            $minuteOptions['invalid_message'] = $options['invalid_message'];
            $secondOptions['invalid_message'] = $options['invalid_message'];
        }

        if (isset($options['invalid_message_parameters'])) {
            $hourOptions['invalid_message_parameters'] = $options['invalid_message_parameters'];
            $minuteOptions['invalid_message_parameters'] = $options['invalid_message_parameters'];
            $secondOptions['invalid_message_parameters'] = $options['invalid_message_parameters'];
        } 

        $hours = $minutes = $seconds = [];        
        foreach ($options['hours'] as $hour) {
            $hours[str_pad(strval($hour), 2, '0', STR_PAD_LEFT)] = $hour;
        }

        $hourOptions['choices'] = $hours;
        $hourOptions['placeholder'] = $options['placeholder']['hour'];
        $hourOptions['choice_translation_domain'] = $options['choice_translation_domain']['hour'];

        foreach ($options['minutes'] as $minute) {
            $minutes[str_pad(strval($minute), 2, '0', STR_PAD_LEFT)] = $minute;
        }
        
        $minuteOptions['choices'] = $minutes;
        $minuteOptions['placeholder'] = $options['placeholder']['minute'];
        $minuteOptions['choice_translation_domain'] = $options['choice_translation_domain']['minute'];

        foreach ($options['seconds'] as $second) {
            $seconds[str_pad(strval($second), 2, '0', STR_PAD_LEFT)] = $second;
        }
        
        $secondOptions['choices'] = $seconds;
        $secondOptions['placeholder'] = $options['placeholder']['second'];
        $secondOptions['choice_translation_domain'] = $options['choice_translation_domain']['second']; 

        $builder
            ->add('hour', ChoiceType::class, $hourOptions)
            ->add('minute', ChoiceType::class, $minuteOptions)
            ->add('second', ChoiceType::class, $secondOptions);
        /*$builder
            ->add('hour', ChoiceType::class, [
                'choices' => $hours,
                'placeholder' => 'Hour', 
                'label' => false,
                'required' => true
            ])
            ->add('minute', ChoiceType::class, [
                'choices' => $minutes,
                'placeholder' => 'Minute',
                'label' => false,
                'required' => true
            ])
            ->add('second', ChoiceType::class, [
                'choices' => $seconds,
                'placeholder' => 'Second',
                'label' => false,
                'required' => true
            ]);*/
        $builder->addModelTransformer(new DurationToSecondsTransformer());
    }

    public function getParent()
    {
        return FormType::class;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $compound = function (Options $options) {
            return true;
        };

        $placeholderDefault = function (Options $options) {
            return $options['required'] ? null : '';
        };

        $placeholderNormalizer = function (Options $options, $placeholder) use ($placeholderDefault) {
            if (\is_array($placeholder)) {
                $default = $placeholderDefault($options);

                return array_merge(
                    ['hour' => $default, 'minute' => $default, 'second' => $default],
                    $placeholder
                );
            }

            return [
                'hour' => $placeholder,
                'minute' => $placeholder,
                'second' => $placeholder,
            ];
        };

        $choiceTranslationDomainNormalizer = function (Options $options, $choiceTranslationDomain) {
            if (\is_array($choiceTranslationDomain)) {
                $default = false;

                return array_replace(
                    ['hour' => $default, 'minute' => $default, 'second' => $default],
                    $choiceTranslationDomain
                );
            }

            return [
                'hour' => $choiceTranslationDomain,
                'minute' => $choiceTranslationDomain,
                'second' => $choiceTranslationDomain,
            ];
        };

        $resolver->setDefaults([
            'hours' => range(0, 23),
            'minutes' => range(0, 59),
            'seconds' => range(0, 59),
            'placeholder' => $placeholderDefault,
            'by_reference' => false,
            'error_bubbling' => false,
            'data_class' => null,
            'empty_data' => function (Options $options) {
                return $options['compound'] ? [] : '';
            },
            'compound' => $compound,
            'choice_translation_domain' => false,
        ]);

        $resolver->setNormalizer('placeholder', $placeholderNormalizer);
        $resolver->setNormalizer('choice_translation_domain', $choiceTranslationDomainNormalizer);

        $resolver->setAllowedTypes('hours', 'array');
        $resolver->setAllowedTypes('minutes', 'array');
        $resolver->setAllowedTypes('seconds', 'array');
    }
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars = array_replace($view->vars, [
            'widget' => 'choice',
            'with_minutes' => true,
            'with_seconds' => true,
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()// To render time_widget
    {
        return 'time';
    }

}

src/Form/Model/Curiosity/CuriosityFormModel.php
<?php
declare(strict_types=1);

namespace App\Form\Model\Curiosity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Entity\User;
use App\Services\ImagesManager\ImagesConstants;

class CuriosityFormModel
{

    private $id;

    /*
        There is no option to change it we dont need assets here
    */
    private $author;

    /**
     * @Assert\NotBlank(message="Please enter title.") 
     * @Assert\Length(
     *      max = 100,
     *      maxMessage = "Title cannot be longer than {{ limit }} characters",
     *      allowEmptyString = false
     * )
     */ 
    private $title;

    /**
     * @Assert\NotBlank(message="Please enter few words of description.")
     * @Assert\Length(
     *      max = 40,
     *      maxMessage = "Description cannot be longer than {{ limit }} characters",
     *      allowEmptyString = false
     * )
     */
    private $description;

    /**
     * //Assert\NotBlank(message="Curiosity must have image.")
     */
    private $mainImageFilename;

    /**
     * @Assert\NotBlank(message="Please enter content.")
     */
    private $content;

    private $isPublished;

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMainImageFilename(): ?string
    {
        return $this->mainImageFilename;
    }

    public function setMainImageFilename(?string $mainImageFilename): self
    {
        $this->mainImageFilename = $mainImageFilename;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }
    
    public function setIsPublished(?bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getImagePath()
    {
        return ImagesConstants::CURIOSITIES_IMAGES.'/'.$this->getAuthor()->getLogin().'/'.$this->getMainImageFilename();
    }

    public function getThumbImagePath()
    {
        return ImagesConstants::CURIOSITIES_IMAGES.'/'.$this->getAuthor()->getLogin().'/'.ImagesConstants::THUMB_IMAGES.'/'.$this->getMainImageFilename();
    }

}

templates/forms/curiosity_form.html.twig
{% block curiosity_form %}
<div class="card-body">
    <h4 class="card-title text-center text-green text-uppercase">{{ header_text }}</h4>
        {{ form_start(curiosityForm, {
            'attr': {
                'class': 'form-larger',
                'id': 'js-curiosity-form',
                'data-url': app.request.getSchemeAndHttpHost()
            },
        }) }}
            {{ form_row(curiosityForm.title, {
                'label' : 'Title: '
            }) }}

            {{ form_row(curiosityForm.description, {
                'label' : 'Description: '
            }) }}
            
            {{ form_row(curiosityForm.imageFile, {
                'label' : 'Main image of curiosity: ',
                attr: {
                    'placeholder': 'Select a curiosity image',
                },
            }) }}


            {% if curiosityForm.vars.data.mainImageFilename is defined and curiosityForm.vars.data.mainImageFilename is not null %}
                <div id="uploaded_image">
                    <p>Already uploaded:</p>
                    <div class="imageForm-container position-relative">
                        <img class="imageForm rounded" src="{{ uploaded_asset(curiosityForm.vars.data.thumbImagePath) }}" alt="Main curiosity image">
                        <div class="image-toolbar">
                            <a href="{{ uploaded_asset(curiosityForm.vars.data.imagePath) }}" target="_blank">
                                <span class="fa fa-search-plus position-absolute link-show"></span>
                            </a>
                            {% if is_granted('ROLE_ADMIN') %}
                                <a 
                                    href="{{ path('api_admin_delete_user_image', 
                                    { id: curiosityForm.vars.data.id }) }}"
                                    id="delete-image"
                                >
                                    <span class="fa fa-trash position-absolute link-delete"></span>
                                </a> 
                            {% else %}
                                <a href="{{ path('api_delete_user_image') }}" id="delete-image">
                                    <span class="fa fa-trash position-absolute link-delete"></span>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                
            {% endif %}

            {% if curiosityForm.author is defined %}
                {{ form_row(curiosityForm.author, {
                    'label' : 'Author: ',
                }) }}
            {% endif %}

            {{ form_row(curiosityForm.content, {
                'label' : 'Content: ',
            }) }}

            {{ form_row(curiosityForm.isPublished, {
                'label' : 'Do You want publish it?'
            }) }}

            <button class="btn btn-lg btn-green float-right text-uppercase" type="submit">{{ button_text }}</button>
        {{ form_end(curiosityForm) }}
</div>
{% endblock %}

templates/forms/registration_form.html.twig
{% block registration_form %}

                    <div class="card-body">
                        <h4 class="card-title text-center text-green text-uppercase">{{ header_text }}</h4>
                            
                            {{ form_start(registrationForm, {
                                'attr': {'class': 'form-signin'}
                            }) }}
                                {% if registrationForm.id is defined %}
                                    {{ form_row(registrationForm.id, {
                                        'label' : 'ID: ',
                                        attr: { class: 'form-id-js' }
                                    }) }}
                                {% endif %}

                                {{ form_row(registrationForm.email, {
                                    'label' : 'E-mail: ',
                                    attr: { placeholder: 'Email' }
                                }) }}

                                {%  if registrationForm.role is defined %}
                                    {{ form_row(registrationForm.role, {
                                        'label' : 'Role: '
                                    }) }}
                                {% endif %}

                                {{ form_row(registrationForm.imageFile, {
                                    'label' : 'Your image: ',
                                    attr: {
                                        'placeholder': 'Select an account image',
                                    }
                                }) }}

                                {% if registrationForm.vars.data.imageFilename is defined and registrationForm.vars.data.imageFilename is not null %}
                                    <div id="uploaded_image">
                                        <p>Already uploaded:</p>
                                        <div class="imageForm-container position-relative">
                                            <img class="imageForm rounded" src="{{ uploaded_asset(registrationForm.vars.data.thumbImagePath) }}" alt="User image">
                                            <div class="image-toolbar">
                                                <a href="{{ uploaded_asset(registrationForm.vars.data.imagePath) }}" target="_blank">
                                                    <span class="fa fa-search-plus position-absolute link-show"></span>
                                                </a>
                                                {% if is_granted('ROLE_ADMIN') %}
                                                    <a 
                                                        href="{{ path('api_admin_delete_user_image', 
                                                        { id: registrationForm.vars.data.id }) }}"
                                                        id="delete-image"
                                                    >
                                                        <span class="fa fa-trash position-absolute link-delete"></span>
                                                    </a> 
                                                {% else %}
                                                    <a href="{{ path('api_delete_user_image') }}" id="delete-image">
                                                        <span class="fa fa-trash position-absolute link-delete"></span>
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    
                                {% endif %}
                            
                                {{ form_row(registrationForm.firstName, {
                                    'label' : 'First Name: ',
                                    attr: { placeholder: 'First Name' }
                                }) }}

                                {{ form_row(registrationForm.secondName, {
                                    'label' : 'Second Name: ',
                                    attr: { placeholder: 'Second Name' }
                                }) }}

                                {{ form_row(registrationForm.gender, {
                                    'label' : 'Gender: '
                                }) }}

                                {% if registrationForm.plainPassword is defined %}
                                    {{ form_row(registrationForm.plainPassword.first, {
                                       'label' : 'Password: ',
                                        attr: { placeholder: 'Password' }
                                    }) }}

                                    {{ form_row(registrationForm.plainPassword.second, {
                                       'label' : 'Repeat password: ',
                                        attr: { placeholder: 'Repeat password' }
                                    }) }}
                                {% endif %}
                                {% if registrationForm.agreeTerms is defined %}
                                    {{ form_row(registrationForm.agreeTerms) }}
                                {% endif %}
                                {%  if registrationForm.birthdate is defined %}
                                    {{ form_row(registrationForm.birthdate, {
                                        'label' : 'Birthdate: '
                                    }) }}

                                    {{ form_row(registrationForm.weight, {
                                        'label' : 'Weight: '
                                    }) }}

                                    {{ form_row(registrationForm.height, {
                                        'label' : 'Height: '
                                    }) }}

                                {% endif %}


                                {% if button_text == 'Register' %}
                                    <div class="form-group">
                                        <div class="g-recaptcha my-3" data-sitekey="{{ public_key }}"></div>
                                        {% if ReCaptchaError is defined %}
                                            <span class="invalid-feedback d-block">
                                                <span class="d-block">
                                                    <span class="form-error-icon badge badge-danger text-uppercase">Error</span> 
                                                    <span class="form-error-message">{{ ReCaptchaError }}</span>
                                                </span>
                                            </span>
                                        {% endif %}
                                    </div>
                                {% endif %}

                                <button class="btn btn-lg btn-green btn-block text-uppercase" type="submit">{{ button_text }}</button>
                            
                            {{ form_end(registrationForm) }}

                    </div>

{% endblock %}

templates/forms/workout_sets_form.html.twig
{%  if workoutForm.durationSecondsTotal is defined %}
    {{ form_row(workoutForm.durationSecondsTotal, {
        'label' : 'Duration: '
    }) }}
{% endif %}
{%  if workoutForm.type is defined %}
    {{ form_row(workoutForm.type) }}
{% endif %}

{# Movement Sets #}
{%  if workoutForm.movementSets is defined %}
    <div class="form-error color-fire">
        {%  if workoutForm.movementSets.parent.vars.errors[0] is defined %}
            {{ workoutForm.movementSets.parent.vars.errors[0].message }}
        {% endif %}
    </div>
    <div id="workout_sets" 
    data-prototype="{{ form_widget(workoutForm.movementSets.vars.prototype)|e }}"
    >
        {% do workoutForm.movementSets.setRendered() %}
        {% for row in workoutForm.movementSets %}
            <div class="card my-2 card-js">
                <div class="card-header bg-info text-white">
                    <strong>SET {{row.vars.name}}</strong>
                </div>
                <div class="card-body">
                    {{ form_row(row) }}
                </div>
                <div class="card-footer bg-secondary text-center">
                    <a href="#" class="btn btn-danger remove-js">Remove set</a>
                </div>
                
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/forms/workout_specific_additional_data_form.html.twig
{# Most activities #}
{%  if workoutSpecificDataForm.durationSecondsTotal is defined %}
    {{ form_row(workoutSpecificDataForm.durationSecondsTotal, {
        'label' : 'Duration: '
    }) }}
{% endif %}

{# Movement #}
{%  if workoutSpecificDataForm.distanceTotal is defined %}
    {{ form_row(workoutSpecificDataForm.distanceTotal, {
        'label' : 'Distance: '
    }) }}
{% endif %}

{%  if workoutSpecificDataForm.type is defined %}
    {{ form_row(workoutSpecificDataForm.type) }}
{% endif %}

{# Movement Sets #}
{%  if workoutSpecificDataForm.movementSets is defined %}
    <div class="form-error color-fire">
        {%  if workoutSpecificDataForm.movementSets.parent.vars.errors[0] is defined %}
            {{ workoutSpecificDataForm.movementSets.parent.vars.errors[0].message }}
        {% endif %}
    </div>
    <div id="workout_sets" 
    data-prototype="{{ form_widget(workoutSpecificDataForm.movementSets.vars.prototype)|e }}"
    >
        {% do workoutSpecificDataForm.movementSets.setRendered() %}
        {% for row in workoutSpecificDataForm.movementSets %}
            <div class="card my-2 card-js">
                <div class="card-header bg-info text-white">
                    <strong>SET {{row.vars.name}}</strong>
                </div>
                <div class="card-body">
                    {{ form_row(row) }}
                </div>
                <div class="card-footer bg-secondary text-center">
                    <a href="#" class="btn btn-danger remove-js">Remove set</a>
                </div>
                
            </div>
        {% endfor %}
    </div>
{% endif %}

{# Bodyweight #}
{%  if workoutSpecificDataForm.repetitionsTotal is defined %}
    {{ form_row(workoutSpecificDataForm.repetitionsTotal, {
        'label' : 'Number of repetitions: '
    }) }}
{% endif %}

{# Weight #}
{%  if workoutSpecificDataForm.dumbbellWeight is defined %}
    {{ form_row(workoutSpecificDataForm.dumbbellWeight, {
        'label' : 'Weight: '
    }) }}
{% endif %}