src/Form/Model/Workout/AbstractWorkoutFormModel.php
<?php
declare(strict_types=1);

namespace App\Form\Model\Workout;

use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AcmeAssert;
use App\Services\ImagesManager\ImagesConstants;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Form\Model\Workout\WorkoutSet\MovementActivitySetFormModel;
use App\Entity\User;
use App\Entity\AbstractActivity;

abstract class AbstractWorkoutFormModel
{

    protected $id;

    /**
     * @Assert\NotBlank(message="Cannot configure user", groups={"model", "bodyweight_model", 
     * "route_model", "weight_model"})
     */
    protected $user;

    /**
     * @Assert\NotBlank(message="Cannot configure activity", groups={"model", 
     * "bodyweight_model", "weight_model", "route_model"})
     */
    protected $activity;

    /**
     * @Assert\NotBlank(message="Your burnout Energy is too small", groups={"model", 
     * "bodyweight_model", "route_model", "weight_model"})
     * @Assert\GreaterThan(message="Your burnout Energy is too small", value=0, 
     * groups={"model", "bodyweight_model", "route_model", "weight_model"})
     */
    protected $burnoutEnergyTotal;

    /**
     * @Assert\NotBlank(message="Please enter date of start", groups={"average_sets", 
     * "specific_sets", "Default", "route_map", "route_model", "weight_model"})
     */
    protected $startAt;
    
    /**
     * @Assert\NotBlank(message="Please enter time", groups={"model", "bodyweight_model",
     *  "Default", "route_model", "weight_model"})
     * @AcmeAssert\NotZeroDuration(groups={"model", "bodyweight_model", "Default", "route_map", "route_model", "weight_model"})
     */
    protected $durationSecondsTotal;

    /**
     *  @Assert\NotBlank(message="Map missing", groups={"route_model"})
     */
    protected $imageFilename;

    /**
     * @Assert\Valid
     * @Assert\Count(
     *      min = 1,
     *      minMessage = "You must specify at least one set",
     *      groups={"specific_sets", "average_sets"}
     * )
     */
    protected $movementSets;

    protected $routeData;

    //helpers
    /**
     * @Assert\NotBlank(message="Please enter activity name", groups={"specific_sets", "route_map"})
     * @Assert\NotNull(message="Please enter activity name", groups={"specific_sets", "route_map"})
     */
    protected $activityName;

    protected $type;


    public function __construct()
    {
        $this->movementSets = new ArrayCollection();
    }

    /**
     * @return Collection|MovementActivitySetFormModel[]
     */
    public function getMovementSets(): Collection
    {
        return $this->movementSets;
    }

    public function addMovementSet(MovementActivitySetFormModel $movementSet): self
    {
        if (!$this->movementSets->contains($movementSet)) {
            $this->movementSets[] = $movementSet;
            $movementSet->setWorkout($this);
        }

        return $this;
    }

    public function removeMovementSet(MovementActivitySetFormModel $movementSet): self
    {
        if ($this->movementSets->contains($movementSet)) {
            $this->movementSets->removeElement($movementSet);
            // set the owning side to null (unless already changed)
            if ($movementSet->getWorkout() === $this) {
                $movementSet->setWorkout(null);
            }
        }

        return $this;
    }

    public function setId(?int $id)
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getActivity(): ?AbstractActivity
    {
        return $this->activity;
    }

    public function setActivity(?AbstractActivity $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function calculateSaveBurnoutEnergyTotal(): self
    {
        $activity = $this->activity;
        $activityEnergy = $activity->getEnergy();

        $workoutDurationTotal = $this->durationSecondsTotal;
        $burnoutEnergyTotal = $activityEnergy * ($workoutDurationTotal/(60*60));

        $this->burnoutEnergyTotal = intval($burnoutEnergyTotal);

        return $this;
    }

    public function setBurnoutEnergyTotal(?int $burnoutEnergyTotal): self
    {
        $this->burnoutEnergyTotal = $burnoutEnergyTotal;

        return $this;
    }

    public function getBurnoutEnergyTotal(): ?int
    {
        return $this->burnoutEnergyTotal;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeInterface $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getDurationSecondsTotal(): ?int
    {
        return $this->durationSecondsTotal;
    }

    public function setDurationSecondsTotal(int $durationSecondsTotal): self
    {
        $this->durationSecondsTotal = $durationSecondsTotal;

        return $this;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setActivityName(string $activityName): self
    {
        $this->activityName = $activityName;

        return $this;
    }

    public function getActivityName(): ?string
    {
        return $this->activityName;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function getRouteData(): ?RouteDataModel
    {
        return $this->routeData;
    }

    public function setRouteData(?RouteDataModel $routeData): self
    {
        $this->routeData = $routeData;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return ImagesConstants::WORKOUTS_IMAGES.'/'.$this->getUser()->getLogin().'/'.$this->getImageFilename();
    }

    public function getThumbImagePath(): ?string
    {
        return ImagesConstants::WORKOUTS_IMAGES.'/'.$this->getUser()->getLogin().'/'.ImagesConstants::THUMB_IMAGES.'/'.$this->getImageFilename();
    }

}

src/Form/Model/Workout/WorkoutSet/MovementActivitySetFormModel.php
<?php
declare(strict_types=1);

namespace App\Form\Model\Workout\WorkoutSet;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Movement version of set activity model to WorkoutModels
 */
class MovementActivitySetFormModel extends AbstractActivitySetFormModel
{

    /**
     * @Assert\NotBlank(message="Distance cannot be blank", groups={"model", "specific_sets"})
     * @Assert\GreaterThan(message="Distance must be greater than 0", value=0, groups={"model", 
     * "specific_sets"})
     */
    private $distance;


    public function getDistance(): ?float
    {
        return $this->distance;
    }

    public function setDistance(?float $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function calculateSaveDistance(): self
    {
        $speedDiff = $this->activity->getSpeedAverageMax() - $this->activity->getSpeedAverageMin();
        $speed = $this->activity->getSpeedAverageMin() + ($speedDiff / 2);

        $distance = $speed * ($this->getDurationSeconds() / 3600);

        $this->distance = $distance;

        return $this;
    }

    public function getAverageSpeed(): ?float
    {
        if($this->getDistance() != null && $this->getDurationSeconds() != null){
            return $this->getDistance()/($this->getDurationSeconds()/3600);
        }

        return null;
    }

    
}

src/Controller/WorkoutController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\WorkoutRepository;
use App\Repository\AbstractActivityRepository;
use App\Entity\Workout;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\WorkoutSpecificDataFormType;
use App\Form\WorkoutAverageDataFormType;
use App\Form\Model\Workout\WorkoutSpecificFormModel;
use App\Form\Model\Workout\WorkoutAverageFormModel;
use App\Services\ModelExtender\WorkoutSpecificExtender;
use App\Services\ModelExtender\WorkoutAverageExtender;
use App\Exception\Api\ApiBadRequestHttpException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Services\ModelValidator\ModelValidatorInterface;
use App\Services\ModelValidator\ModelValidatorChooser;
use App\Services\Factory\Workout\WorkoutFactory;
use App\Services\Updater\Workout\WorkoutUpdaterInterface;
use Symfony\Component\Messenger\MessageBusInterface;
use App\Message\Command\DeleteWorkoutImage;
use App\Services\ImagesManager\ImagesManagerInterface;
use App\Services\JsonErrorResponse\JsonErrorResponseFactory;
use App\Services\JsonErrorResponse\JsonErrorResponseTypes;
use App\Services\FormApiValidator\FormApiValidatorInterface;
use App\Services\Factory\WorkoutModel\WorkoutModelFactory;

class WorkoutController extends AbstractController
{
    /**
     * @Route("/workout/list", name="workout_list")
     * @IsGranted("ROLE_USER")
     */
    public function list(WorkoutRepository $workoutRepository, AbstractActivityRepository $activityRepository)
    {
    	$user = $this->getUser();
    	$workouts = $workoutRepository->findBy([ 'user' => $user ]);
        $movementActivitiesNames = $activityRepository->findByTypeUniqueNamesAlphabetical('Movement');

        $formAverage = $this->createForm(WorkoutAverageDataFormType::class);
        $formSpecific = $this->createForm(WorkoutSpecificDataFormType::class);

        return $this->render('workout/list.html.twig', [
            'workouts' => $workouts,
            'workoutForm' => $formAverage->createView(),
            'formSpecific' => $formSpecific->createView(),
            'movementActivities' => $movementActivitiesNames
        ]);

    }
    
    /**
     * @Route("/workout/stats", name="workout_stats", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function stats()
    {
        return $this->render('workout/stats.html.twig');
    }

    /**
     * @Route("api/workout/get_id_by_date", name="api_workout_id_by_date")
     * @IsGranted("ROLE_USER")
     */
    public function getWorkoutIdByDateAction(WorkoutRepository $workoutRepository, Request $request)
    {
        $timeline = json_decode($request->getContent(), true);

        if($timeline === null) {
            throw new ApiBadRequestHttpException('Invalid JSON.');    
        }

        $timeline['stopDate'] .= ' 23:59:59';
        $user = $this->getUser();
        $workouts = $workoutRepository->findByUserAndDateArray($user, $timeline);
       // $workouts = $workoutRepository->findByUserAndDateArrayNative($user, $timeline);

        //$workouts = $workoutRepository->findByUserAndDate($user, $timeline); if we want whole workout object
        
        return $this->json(
            $workouts,
            200,
            [],
            []
        );

    }

    /**
     * @Route("api/workout/get_energy_by_date", name="api_workout_energy_by_date")
     * @IsGranted("ROLE_USER")
     */
    public function getWorkoutEnergyByDateAction(WorkoutRepository $workoutRepository, Request $request)
    {
        $days = json_decode($request->getContent(), true);

        if($days === null) {
            throw new ApiBadRequestHttpException('Invalid JSON.');    
        }

        $timeline['startDate'] = $days[0];
        $timeline['stopDate'] = end($days);
        $timeline['stopDate'] .= ' 23:59:59';//To get all workouts during the last day

        /**
         * @var User $user
         */
        $user = $this->getUser();
        $workouts = $workoutRepository->countEnergyPerDayByUserAndDateArray($user, $timeline);

        $energyPerDay = array();
        $index = 0;

        if(!empty($workouts)) {
            foreach ($days as $day) {
                if (array_key_exists($index, $workouts) && $day == $workouts[$index]['startDate']) {
                    $currentEnergy = $workouts[$index]['burnoutEnergy'];
                    $index++;
                } else {
                    $currentEnergy = 0;
                }

                array_push($energyPerDay, $currentEnergy);
            }
        } else {
            foreach ($days as $day) {
                $currentEnergy = 0;
                array_push($energyPerDay, $currentEnergy);
            }
        }

        return $this->json(
            $energyPerDay,
            200,
            [],
            []
        );
    }

    /**
     * @Route("/workout/choose_add", name="workout_choose_add", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function addPanel()
    {
    
        return $this->render('workout/addPanel.html.twig', []);
    }

    /**
     * @Route("/workout/add_average", name="workout_add_average", methods={"POST", "GET"})
     * @IsGranted("ROLE_USER")
     */
    public function addAverage(Request $request, EntityManagerInterface $entityManager, WorkoutAverageExtender $workoutAverageExtender, ModelValidatorInterface $modelValidator, ModelValidatorChooser $validatorChooser)
    {
        $formAverage = $this->createForm(WorkoutAverageDataFormType::class);
        $formAverage->handleRequest($request);

        if ($formAverage->isSubmitted() && $formAverage->isValid()) {
            $workoutAverageFormModel = $formAverage->getData();
            $workoutAverageFormModel = $workoutAverageExtender->fillWorkoutModel($workoutAverageFormModel, $this->getUser(), $formAverage['imageFile']->getData());  
            
            if($workoutAverageFormModel) {
                //Validation Model data
                $validationGroup = $validatorChooser->chooseValidationGroup($workoutAverageFormModel->getType());
                $isValid = $modelValidator->isValid($workoutAverageFormModel, $validationGroup);
                    
                if ($isValid) {
                    try {
                        $activity = $workoutAverageFormModel->getActivity();
                        $workoutFactory = WorkoutFactory::chooseFactory($activity->getType());
                        $workout = $workoutFactory->create($workoutAverageFormModel);

                        $entityManager->persist($workout);
                        $entityManager->flush();

                        $this->addFlash('success', 'Workout was added!');
                        return $this->redirectToRoute('workout_list');
                    } catch (\Exception $e) {
                        $this->addFlash('warning', $e->getMessage());
                        return $this->render('workout/add_average.html.twig', [
                            'workoutForm' => $formAverage->createView(),
                        ]);
                    }

                } else {
                    $errors = $modelValidator->getErrors();
                    return $this->render('workout/add_average.html.twig', [
                        'workoutForm' => $formAverage->createView(),
                        'errors' => $errors,
                    ]);
                }
            }
            $this->addFlash('warning', 'Cannot create workout with that type of activity.');
        }

        return $this->render('workout/add_average.html.twig', [
            'workoutForm' => $formAverage->createView(),
        ]);
    }

    /**
     * @Route("/workout/add_specific", name="workout_add_specific", methods={"POST", "GET"})
     * @IsGranted("ROLE_USER")
     */
    public function addSpecific(Request $request, EntityManagerInterface $entityManager, WorkoutSpecificExtender $workoutSpecificExtender, ModelValidatorInterface $modelValidator, ModelValidatorChooser $validatorChooser)
    {
        $formSpecific = $this->createForm(WorkoutSpecificDataFormType::class);
            
        $formSpecific->handleRequest($request);
        if ($formSpecific->isSubmitted() && $formSpecific->isValid()) {
            $workoutSpecificModel = $formSpecific->getData();
            $workoutSpecificModel = $workoutSpecificExtender->fillWorkoutModel($workoutSpecificModel, $this->getUser(), $formSpecific['imageFile']->getData());

            if ($workoutSpecificModel) {
                //Validation Model data
                $validationGroup = $validatorChooser->chooseValidationGroup($workoutSpecificModel->getType());
                $isValid = $modelValidator->isValid($workoutSpecificModel, $validationGroup);

                if ($isValid) {
                    try {
                        $workoutFactory = WorkoutFactory::chooseFactory($workoutSpecificModel->getType());
                        $workout = $workoutFactory->create($workoutSpecificModel);

                        $entityManager->persist($workout);
                        $entityManager->flush();

                        $this->addFlash('success', 'Workout was added!');
                        return $this->redirectToRoute('workout_list');
                    } catch (\Exception $e) {
                        $this->addFlash('warning', $e->getMessage());
                        return $this->render('workout/add_specific.html.twig', [
                            'workoutSpecificDataForm' => $formSpecific->createView(),
                        ]);
                    }

                } else {
                    $errors = $modelValidator->getErrors();
                    return $this->render('workout/add_specific.html.twig', [

templates/workout/addPanel.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Add Workout Panel{% endblock %}

{% block section_class %}addWorkoutPanel{% endblock %} 

{% block content_class %}{{ parent() }} container-border-blue bg-profile text-center p-2{% endblock %} 
{% block content_body %}
        <div class="col-sm-10 p-3 mx-auto  my-3 link-card">
            <a href="{{ path('workout_add_average') }}" class="stretched-link">
                <div class="card bg-transparent border-0">
                    <div class="row no-gutters">
                        <div class="col-auto">
                            <img src="//placehold.it/100" class="img-fluid" alt="">
                        </div>
                        <div class="col">
                            <div class="card-block px-2">
                                <h4 class="card-title text-left title-style">New workout without tracking route</h4>
                                <p class="card-text text-left"><small>Choose this option if the workout doesn't have a route, e.g. if you worked out in a gym, or if you just don't want to bother picking a route for your workout.</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-10 p-3 mx-auto  my-3 link-card">
            <a href="{{ path('route_workout_track_route') }}" class="stretched-link">
                <div class="card bg-transparent border-0">
                    <div class="row no-gutters">
                        <div class="col-auto">
                            <img src="//placehold.it/100" class="img-fluid" alt="">
                        </div>
                        <div class="col">
                            <div class="card-block px-2">
                                <h4 class="card-title text-left title-style">New workout with tracking route</h4>
                                <p class="card-text text-left"><small>Choose this option if you want track your workout route.</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-10 p-3 mx-auto  my-3 link-card">
            <a href="{{ path('route_workout_draw_route') }}" class="stretched-link">
                <div class="card bg-transparent border-0">
                    <div class="row no-gutters">
                        <div class="col-auto">
                            <img src="//placehold.it/100" class="img-fluid" alt="">
                        </div>
                        <div class="col">
                            <div class="card-block px-2">
                                <h4 class="card-title text-left title-style">New workout with drawed route</h4>
                                <p class="card-text text-left"><small>Choose this option if you wanna draw route of workout.</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
{% endblock %}

{% block javascripts %}
{{ parent() }}

{% endblock %}




    

templates/workout/add_average.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Add Workout{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css">
    <link rel="stylesheet" href="{{ asset('css/_login.css') }}">
{% endblock %}
{% block section_class %}addWorkout{% endblock %} 
{% block content_class %}{% endblock %}
{% block content_body %}
	      	<div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
		        <div class="card card-signin my-5 shadow-box">
                    <ul class="nav nav-pills nav-fill">
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ path('workout_add_average') }}">Average data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('workout_add_specific') }}">Specific data</a>
                        </li>
                    </ul>
                    {{ include('forms/workout_average_data_form.html.twig', {
                        header_text: 'Add new Workout',
                        button_text: 'Add'
                    }) }}
		        </div>
	      	</div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script type="module" src="{{ asset('js/_apiHelper.js') }}"></script>
    <script type="module" src="{{ asset('js/_formHelper.js') }}"></script>
    <script type="module" src="{{ asset('js/_workoutSets.js') }}"></script>
    
    <!-- Upload image --> 
    <script type="module" src="{{ asset('js/_uploadImageForm.js') }}"></script>
    <script>
    $(document).ready(function() {
        
        $('.js-datepicker').datetimepicker({
            format:'Y-m-d H:i'
        });
    });
    </script>
{% endblock %}

templates/workout/report.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Wokout Report{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block section_class %}workoutReport{% endblock %} 
{% block content_class %}{% endblock %}
{% block content_body %}
<div class="col-sm-12 col-md-10 mx-auto">
    <div class="card card-signin my-5 shadow-box">
        <div class="card-header">
            <div class="row">
                <div class="col-10">
                    <span class="d-block text-muted text-uppercase">
                        {{ workout.activity.name }}
                    </span>
                    <span class="d-block text-muted">
                        <small>{{ workout.startAt | date('Y-m-d H:i') }}</small>
                    </span>
                </div>
                <div class="col-2">
                    <a href="{{ path('workout_list') }}" class="btn btn-primary float-right">
                        <span class="fas fa-clipboard-list"></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body p-0 ">
            <div class="card-text row no-gutters">
                <div class="col-md-5">
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-fire color-fire"></span>
                        <span class="text-muted text-uppercase">
                            Burnout Energy
                            {{workout.burnoutEnergyTotal }} kcal
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="far fa-clock color-clock"></span>
                        <span class="text-muted text-uppercase">
                            Duration
                            {{ workout.durationSecondsTotal | time }}
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-running text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Average Speed 
                            {% if workout.averageSpeed %}
                                {{ workout.averageSpeed | number_format(2) }}
                            {% else %}
                                ---
                            {% endif %}
                            km/h
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-tachometer-alt text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Average Pace
                            {% if workout.averagePace %}
                                {{ workout.averagePace | number_format(2) }}
                            {% else %}
                                ---
                            {% endif %}
                            min/km
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-road color-clock"></span>
                        <span class="text-muted text-uppercase">
                            Distance
                            {% if workout.distanceTotal %}
                                {{ workout.distanceTotal | number_format(2) }}
                            {% else %}
                                ---
                            {% endif %}
                            km
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-mountain text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Min Altitude
                            {% if workout.routeData.altitudeMin is defined %}
                                {{ workout.routeData.altitudeMin | number_format(2) }}
                            {% else %}
                                ---
                            {% endif %}
                            m
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-mountain text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Max Altitude
                            {% if workout.routeData.altitudeMax is defined %}
                                {{ workout.routeData.altitudeMax | number_format(2) }}
                            {% else %}
                                ---
                            {% endif %}
                            m
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-thermometer-half text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Average Temperature
                            {% if workout.routeData.temperature is defined and workout.routeData.temperature %}
                                {{ workout.routeData.temperature }} &#x2103;
                            {% else %}
                                ---
                            {% endif %}
                        </span>
                    </div>
                    <div class="col-12 text-center py-2 border">
                        <span class="fas fa-cloud-sun text-primary"></span>
                        <span class="text-muted text-uppercase">
                            Weather Conditions
                            {% if workout.routeData.weatherConditions is defined and workout.routeData.weatherConditions %}
                                "{{ workout.routeData.weatherConditions }}"
                            {% else %}
                                ---
                            {% endif %}
                        </span>
                    </div>
                </div>
                <div class="col-md-7">
                    {% if workout.imageFilename is not null %} 
                        <img class="img-fluid" src="{{ uploaded_asset(workout.imagePath) }}" alt="Workout image">
                    {% else %}
                        <img class="w-100 img-fluid" src="https://via.placeholder.com/350" alt="Workout image">
                    {% endif %}            
                </div>
            </div>
        </div>             
    </div>
</div>

{% endblock %}